### ISSUE TITLE
Non-blocking?

### ISSUE THREAD

**Issue by scalp42** [schmurfy/ruby-supervisor#5]
Thanks for the gem, I'm curious if there's a way to kick a process restart without waiting for the answer from Supervisor ?

Thanks in advance!

**Comment by schmurfy** [comment]
Yes you can but the way the supervisor api is designed we only have a start and stop command so the way it is implemented in this gem is that it stops and then starts it, in non blocking mode a new thread is spawned to do the same.

You can ask the library to restart without blocking by calling `restart(false)`, you can have a look at https://github.com/schmurfy/ruby-supervisor/blob/master/lib%2Fruby-supervisor%2Fapi%2Fprocess.rb?ts=2#L74 to see what really happens behind the scene.

**Comment by scalp42** [comment]
Perfect @schmurfy thanks for the answer!

Closing.
